### ISSUE TITLE
TypeError: actionhero.Process is not a constructor

### ISSUE THREAD

**Issue by maxLogvynyuk** [actionhero/actionhero-tutorial#180]
I running test script  ( "test": "jest",) and get next error:
![actionhero_1Process](https://user-images.githubusercontent.com/59360889/106919226-9d3c9e80-6712-11eb-9381-c7727ca0687c.png)

Jest configuration:
  "jest": {
    "testEnvironment": "node",
    "moduleDirectories": [
      "node_modules"
    ],
    "moduleFileExtensions": [
      "js",
      "jsx",
      "ts",
      "tsx",
      "json"
    ],
    "transform": {
      "^.+\\.ts?$": "ts-jest"
    }
  }

server.ts

![image](https://user-images.githubusercontent.com/59360889/106920406-b8f47480-6713-11eb-9a7d-4b1c5b895c30.png)

Console in server.js after build and executing jest show next:
![image](https://user-images.githubusercontent.com/59360889/106919893-37044b80-6713-11eb-8bec-9f0158881296.png)

Seems like  class  Process don`t importing.

I have some tests and passed successfully only first every time.

Example of test:
![image](https://user-images.githubusercontent.com/59360889/106921677-e7bf1a80-6714-11eb-9eae-562c849326a4.png)

**Comment by evantahler** [comment]
It looks like your error is not with this tutorial project, but something new `actionhero-docker-compose`.  Please make an issue in the https://github.com/actionhero/actionhero repo or start a discussion.   You'll ned to provide code which can reproduce the error so we can help you out. 

If you are having trouble with docker compose, there's an example here - https://github.com/actionhero/actionhero/blob/master/docker-compose.yml
