### ISSUE TITLE
getting started: ActionheroClient is undefined

### ISSUE THREAD

**Issue by veakey** [actionhero/actionhero-tutorial#35]
### Edit: done with Archlinux
```shell
Linux -no-lo-se- 4.14.31-1-MANJARO #1 SMP PREEMPT Wed Mar 28 21:42:49 UTC 2018 x86_64 GNU/Linux

npm: 5.6.0
node: 8.11.1
```

Just freshly
*  cloned the repo
*  npm install
*  npm start

Everything went fine but client side there is an error which blocks the UI flow (some UI elements are not displayed)
```
ReferenceError: ActionheroClient is not defined
```
### Result of fresh install
![screenshot-2018-4-10 actionhero js](https://user-images.githubusercontent.com/6059287/38545169-b718b578-3ca9-11e8-8cd7-f4396d3c8d3e.png)

Quick and dirty solutions

*  change ActionheroClient in html files to ActionheroWebsocketClient
or
*  append this dummy code to actionheroClient.min.js
```javascript
ActionheroClient=ActionheroWebsocketClient;
```

Once it's fixed the UI is more complete and we can **almost** test the socket chat

![screenshot-2018-4-10 actionhero js 1](https://user-images.githubusercontent.com/6059287/38545442-58f11552-3caa-11e8-8767-dee2eccc32de.png)

Hope you will fix it for newer users

Thanks

--
veakey

**Comment by evantahler** [comment]
Thanks for pointing this out!
Fixed in https://github.com/actionhero/actionhero-tutorial/pull/36

**Comment by veakey** [comment]
Welcome, thanks you too ;)
