### ISSUE TITLE
Generated Initializer syntax

### ISSUE THREAD

**Issue by garrettboatman** [actionhero/actionhero-tutorial#37]
For Initializers, the [docs syntax](https://docs.actionherojs.com/ActionHero.Initializer.html) uses:
```
const {Initializer, api} = require('actionhero')

module.exports = class StuffInit extends Initializer {
  constructor () {
    super()
    this.name = 'StuffInit'
    this.loadPriority = 1000
    this.startPriority = 1000
    this.stopPriority = 1000
  }

  async initialize () {
    api.StuffInit = {}
    api.StuffInit.doAThing = async () => {}
    api.StuffInit.stopStuff = async () => {}
    api.log('I initialized', 'debug', this.name)
  }

  async start () {
    await api.StuffInit.startStuff()
    api.log('I started', 'debug', this.name)
  }

  async stop () {
    await api.StuffInit.stopStuff()
    api.log('I stopped', 'debug', this.name)
  }
}
```

But my generator is creating this:
```
'use strict'
const ActionHero = require('actionhero')

module.exports = class MyInitializer extends ActionHero.Initializer {
  constructor () {
    super()
    this.name = 'users'
    this.loadPriority = 1000
    this.startPriority = 1000
    this.stopPriority = 1000
  }

  async initialize () {
    ActionHero.api['users'] = {}
  }

  async start () {}
  async stop () {}
}
```

Small change, but it seems like old syntax.
Is this an option in config? Or is it a version issue? I'm on `19.0.1`.

**Comment by evantahler** [comment]
That looks the same to me other than the decomposition of the `Actionhero` object from the require statement.   Would you prefer decomposed `const {Initializer, api} = require('actionhero')` rather than dot-access `const ActionHero = require('actionhero'); ActionHero. Initializer `?

**Comment by garrettboatman** [comment]
Thanks for the quick reply.
I do like the decomposed variable syntax. It threw me off that the examples showed different syntax than the generator, but not a huge deal.

**Comment by evantahler** [comment]
With generators, we use the full object, because we don't know what parts you might need.  I'll close this then
